title: "I.N.G"
email: t@okzk.org
description: > # this means to ignore newlines until "baseurl:"
  If you wish to make apple pie from scratch, you must first create the universe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://okzk.org" # the base hostname & protocol for your site
twitter_username: tokzk
github_username:  tokzk

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# # Custom vars
# # version:  2.1.0

paginate: 10

# lsi: true

gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-amazon
  - jekyll-archives
  - jekyll-sitemap


assets:
  autowrite: true
  prefix: "/assets"
  digest: false
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js

sass:
  sass_dir: _sass

deploy:
- rsync -az -e ssh --delete . okzk:~/www/okzk.org/

exclude: ["Gemfile", "Gemfile.lock", "README.md", "bin"]

permalink: /blog/:title

jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/:name/'
