# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "I.N.G"
email: t@okzk.org
description: > # this means to ignore newlines until "baseurl:"
  If you wish to make apple pie from scratch, you must first create the universe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.okzk.org" # the base hostname & protocol for your site
twitter_username: tokzk
github_username:  tokzk

# Build settings
markdown: kramdown

kramdown:
  input: GFM

# Custom vars
version:  2.1.0

paginate: 5

gems:
  - jekyll-paginate
  - jekyll-amazon
  - jekyll-archives
  - jekyll-sitemap

deploy:
- rsync -az -e ssh --delete . okzk:~/www/blog.okzk.org/

exclude: ["Gemfile", "Gemfile.lock"]

permalink: pretty

jekyll-archives:
  enabled:
    - categories
  layout: 'archive'
  permalinks:
    category: '/:name/'
